vim.g.mapleader = " "
vim.keymap.set("i", "<S-tab>", "<C-d>")
vim.keymap.set("i", "<tab>", "<C-t>")
vim.keymap.set("n", "<leader>nh", vim.cmd.noh)
vim.keymap.set("n", "<leader>ft", vim.cmd.NvimTreeToggle)
vim.keymap.set("n", "<leader>tf", vim.cmd.NvimTreeFindFile)
vim.keymap.set("n", "<leader>q", vim.cmd.BufferClose)
vim.keymap.set("n", "<C-w>", vim.cmd.BufferClose)
vim.keymap.set("n", "<leader>j", "<C-W>j")
vim.keymap.set("n", "<leader>k", "<C-W>k")
vim.keymap.set("n", "<leader>l", "<C-W>l")
vim.keymap.set("n", "<leader>h", "<C-W>h")
vim.keymap.set("i", "kj", "<Esc>")
vim.keymap.set("n", "<leader><S-tab>", vim.cmd.BufferPrevious)
vim.keymap.set("n", "<leader><tab>", vim.cmd.BufferNext)
vim.keymap.set("n", "<leader>rb", vim.cmd.BufferRestore)
vim.keymap.set("n", "<leader>rl", function()
  vim.opt.relativenumber = not vim.opt.relativenumber:get()
end)
-- reload config file
vim.keymap.set("n", "<leader>rc", function()
  vim.cmd("source $MYVIMRC")
  print("Configs reloaded.")
end)
