vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.expandtab = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.smartindent = true
vim.opt.termguicolors = true
vim.g.mapleader = " "
vim.opt.guifont = { "Iosevka", "h24" }
vim.opt.clipboard = "unnamedplus"
vim.g.gitblame_delay = 1000
