local builtin = require('telescope.builtin')
local telescope = require("telescope")
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<C-g>', builtin.find_files, {})
vim.keymap.set('n', '<C-S-f>', function()
  builtin.grep_string({ search = vim.fn.input("Grep > ") });
end)
vim.keymap.set('n', '<leader>ta', function()
  telescope.extensions.vstask.tasks()
end)
